const en = {
  SIGN_IN: "Sign In",
  SIGN_UP: "Sign Up",
  LOG_IN: "Log In",
  LOG_OUT: "Log out",
  SEND: "Send",
  USERNAME_PLACEHOLDER: "User Name",
  EMAIL_PLACEHOLDER: "Email Address",
  PASSWORD_PLACEHOLDER: "Password",
  SIGN_IN_LINK: "Click here to sign in",
  SIGN_UP_LINK: "Click here to sign up",
  LAUNCH_ROOM_TITLE: "Launch Room",
  LAUNCH_ROOM_BUTTON_TITLE: "Launch Room",
  LAUNCH_ROOM_LINK_TITLE: "Already have a room?",
  JOIN_TITLE: "Join",
  JOIN_ROOM_TITLE: "Join Room",
  JOIN_ROOM_BUTTON_TITLE: "Join Room",
  JOIN_ROOM_LINK_TITLE: "If you don't have a room yet create it here",
  ROOM_USERNAME_PLACEHOLDER: "Name",
  ROOMNAME_PLACEHOLDER: "Room Name",
  FIND_ROOMS: "Find Room",
  CLOSE: "Close",
  LOAD_MORE: "Load More",
};

export { en };
